### ISSUE TITLE
Newly copied cheats lack write permissions

### ISSUE THREAD

**Issue by renfredxh** [chrisallenlane/cheat#207]
So I started using cheat on my new system (OSX 10.10) and wanted to edit an existing cheat using `-e` but ran into an issue. Seems like when cheats are copied the `DEFAULT_CHEAT_DIR` the permissions remain read-only, so changes can't be saved. And when trying to edit them again cheat checks to see if the new file `is_writeable` which returns false so it tries to copy that file again but throws an error since the new cheat file already exists. 

Strangely this didn't happen when I was using cheat on linux so I'm not sure if it's something different with my setup or what, but either way maybe adding a quick call to `os.chmod` in `create_or_edit` after copying a new cheat to add write permissions would help. 

Here's an example of what I'm talking about:
```console
00:23:22-renfred@wartortle~$ ls -l ~/.dotfiles/link/.cheat
total 24
-rw-r--r--  1 renfred  staff   132 Jan 28 11:19 grails
-rw-r--r--  1 renfred  staff   598 Feb  3 00:15 mysql
-rw-r--r--  1 renfred  staff  1700 Feb  3 00:15 vim
00:23:31-renfred@wartortle~$ cheat -e git
The git sheet is not editable. Do you want to copy it to your user cheatsheets directory before editing? Keep in mind that your sheet will always be used before system-wide one.
[y/n] y
# Editor opens up here in read-only mode
00:23:50-renfred@wartortle~$ ls -l ~/.dotfiles/link/.cheat
total 32
-r--r--r--  1 renfred  staff  1909 Feb  3 00:23 git
-rw-r--r--  1 renfred  staff   132 Jan 28 11:19 grails
-rw-r--r--  1 renfred  staff   598 Feb  3 00:15 mysql
-rw-r--r--  1 renfred  staff  1700 Feb  3 00:15 vim
00:23:54-renfred@wartortle~$ cheat -e git
The git sheet is not editable. Do you want to copy it to your user cheatsheets directory before editing? Keep in mind that your sheet will always be used before system-wide one.
[y/n] y
# Editor opens up again, read-only mode
Traceback (most recent call last):
  File "/usr/local/Cellar/cheat/2.1.3/libexec/bin/cheat", line 53, in <module>
    sheet.create_or_edit(options['<cheatsheet>'])
  File "/usr/local/Cellar/cheat/2.1.3/lib/python2.7/site-packages/cheat/sheet.py", line 44, in create_or_edit
    copy(path(sheet), os.path.join(sheets.default_path(), sheet))
  File "/usr/local/Cellar/cheat/2.1.3/lib/python2.7/site-packages/cheat/sheet.py", line 14, in copy
    shutil.copy(current_sheet_path, new_sheet_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `/Users/renfred/.cheat/git` and `/Users/renfred/.cheat/git` are the same file
00:24:03-renfred@wartortle~$ chmod +w ~/.dotfiles/link/.cheat/git
00:24:23-renfred@wartortle~$ cheat -e git
# Editor opens here and cheat can be edited normally
```

**Comment by chrisallenlane** [comment]
@renfredxh, thanks very much for the ticket. This issue should now be resolved in cheat version `2.1.5` :)
